theme: jekyll-theme-cayman
title: "Things I Wish I Had Known About Applying for College"
description: "A crowd-sourced attempt to provide non-obvious advice on applying to college"
# url: https://wish-i-had-known.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
# baseurl: "" # the subpath of your site, e.g. "/blog"
